#Atual
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'us-docker.pkg.dev/project-2ea52c4e-c1c9-49d6-8a8/app-repo/app',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'us-docker.pkg.dev/project-2ea52c4e-c1c9-49d6-8a8/app-repo/app'
  ]

images:
- 'us-docker.pkg.dev/project-2ea52c4e-c1c9-49d6-8a8/app-repo/app'